require 'erb'

require_relative 'ruby/syntax'
require_relative 'ruby/program'
require_relative 'ruby/comment'
require_relative 'ruby/self_evaluating'
require_relative 'ruby/self'
require_relative 'ruby/nil'
require_relative 'ruby/boolean'
require_relative 'ruby/integer'
require_relative 'ruby/float'
require_relative 'ruby/string'
require_relative 'ruby/symbol'
require_relative 'ruby/hash_literal'
require_relative 'ruby/array_literal'
require_relative 'ruby/identifier'
require_relative 'ruby/constant'
require_relative 'ruby/block_variable'
require_relative 'ruby/instance_variable'
require_relative 'ruby/assignment'
require_relative 'ruby/method'
require_relative 'ruby/macro'
require_relative 'ruby/send'
require_relative 'ruby/class'
require_relative 'ruby/module'
require_relative 'ruby/function_application'
require_relative 'ruby/operator'
require_relative 'ruby/binary_operation'
require_relative 'ruby/unary_operation'

require_relative 'ruby/if_clause'
require_relative 'ruby/elsif_clause'
require_relative 'ruby/else'
require_relative 'ruby/end'
require_relative 'ruby/if'

require_relative 'ruby/return'
