require 'erb'

require_relative 'ruby/syntax'
require_relative 'ruby/self_evaluating'
require_relative 'ruby/integer'
require_relative 'ruby/float'
require_relative 'ruby/string'
require_relative 'ruby/symbol'
require_relative 'ruby/hash_literal'
require_relative 'ruby/array_literal'
require_relative 'ruby/identifier'
require_relative 'ruby/block_variable'
require_relative 'ruby/instance_variable'
require_relative 'ruby/assignment'
require_relative 'ruby/method'
require_relative 'ruby/class'
require_relative 'ruby/method_call'
require_relative 'ruby/method_resolution'
